version: '3.8'

services:
  db:
    image: "postgres:12"
    container_name: postgres_db1
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    env_file:
      - .env

volumes:
  postgres_data: